import { toolMeta } from '@/stores/HistoryStore'

export function useExport() {

  /**
   * Generate markdown summary of a decision
   */
  function generateMarkdown(decision) {
    const meta = toolMeta[decision.tool] || { name: decision.tool }
    const date = new Date(decision.createdAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })

    let md = `# Decision Analysis: ${decision.decision}\n\n`
    md += `**Tool:** ${meta.name}\n`
    md += `**Date:** ${date}\n`
    md += `**Score:** ${decision.score !== null ? decision.score : 'N/A'}\n`
    md += `**Recommendation:** ${decision.recommendation}\n\n`

    // Add tool-specific details
    if (decision.data) {
      md += generateToolDetails(decision.tool, decision.data)
    }

    if (decision.outcome) {
      md += `## Outcome\n`
      md += `**Rating:** ${decision.outcome.rating}/10\n`
      if (decision.outcome.notes) {
        md += `**Notes:** ${decision.outcome.notes}\n`
      }
      md += `**Tracked:** ${new Date(decision.outcome.trackedAt).toLocaleDateString()}\n`
    }

    md += `\n---\n*Generated by Decision Tools*`

    return md
  }

  /**
   * Generate tool-specific details in markdown
   */
  function generateToolDetails(tool, data) {
    let details = `## Analysis Details\n\n`

    switch (tool) {
      case 'tententen':
        details += `### Time Perspectives\n`
        details += `- 10 Minutes: ${data.feel10min}/100\n`
        details += `- 10 Months: ${data.feel10months}/100\n`
        details += `- 10 Years: ${data.feel10years}/100\n`
        break

      case 'regret':
        details += `### Regret Factors\n`
        details += `- Regret of Inaction: ${data.regretNotTrying}/100\n`
        details += `- Reversibility: ${data.reversibility}/100\n`
        details += `- Value Alignment: ${data.valueAlignment}/100\n`
        details += `- 80-Year Perspective: ${data.age80Perspective}/100\n`
        break

      case 'pmi':
        details += `### Plus\n`
        data.plusItems?.filter(i => i.text).forEach(i => {
          details += `- ${i.text} (${i.weight})\n`
        })
        details += `\n### Minus\n`
        data.minusItems?.filter(i => i.text).forEach(i => {
          details += `- ${i.text} (${i.weight})\n`
        })
        details += `\n### Interesting\n`
        data.interestingItems?.filter(i => i.text).forEach(i => {
          details += `- ${i.text} (${i.weight})\n`
        })
        break

      case 'swot':
        details += `### Strengths\n`
        data.strengths?.filter(i => i.text).forEach(i => {
          details += `- ${i.text} (+${i.weight})\n`
        })
        details += `\n### Weaknesses\n`
        data.weaknesses?.filter(i => i.text).forEach(i => {
          details += `- ${i.text} (-${i.weight})\n`
        })
        details += `\n### Opportunities\n`
        data.opportunities?.filter(i => i.text).forEach(i => {
          details += `- ${i.text} (+${i.weight})\n`
        })
        details += `\n### Threats\n`
        data.threats?.filter(i => i.text).forEach(i => {
          details += `- ${i.text} (-${i.weight})\n`
        })
        break

      case 'opportunityCost':
        details += `### What You Gain\n`
        data.gains?.filter(i => i.text).forEach(i => {
          details += `- ${i.text} (+${i.weight})\n`
        })
        details += `\n### What You Sacrifice\n`
        data.sacrifices?.filter(i => i.text).forEach(i => {
          details += `- ${i.text} (-${i.weight})\n`
        })
        break

      case 'coinFlip':
        details += `### Coin Flip Result\n`
        details += `- Option A: ${data.optionA}\n`
        details += `- Option B: ${data.optionB}\n`
        details += `- Coin landed on: ${data.result === 'A' ? data.optionA : data.optionB}\n`
        details += `- Your reaction: ${data.reaction}\n`
        break

      case 'fearRegret':
        details += `### Fears of Action\n`
        data.fearsOfAction?.filter(i => i.text).forEach(i => {
          details += `- ${i.text} (${i.weight})\n`
        })
        details += `\n### Fears of Inaction\n`
        data.fearsOfInaction?.filter(i => i.text).forEach(i => {
          details += `- ${i.text} (${i.weight})\n`
        })
        break
    }

    return details + '\n'
  }

  /**
   * Generate plain text summary
   */
  function generatePlainText(decision) {
    const meta = toolMeta[decision.tool] || { name: decision.tool }
    const date = new Date(decision.createdAt).toLocaleDateString()

    let text = `DECISION ANALYSIS\n`
    text += `${'='.repeat(50)}\n\n`
    text += `Decision: ${decision.decision}\n`
    text += `Tool: ${meta.name}\n`
    text += `Date: ${date}\n`
    text += `Score: ${decision.score !== null ? decision.score : 'N/A'}\n`
    text += `Recommendation: ${decision.recommendation}\n`
    text += `\n${'='.repeat(50)}\n`
    text += `Generated by Decision Tools`

    return text
  }

  /**
   * Copy text to clipboard
   */
  async function copyToClipboard(text) {
    try {
      await navigator.clipboard.writeText(text)
      return true
    } catch (err) {
      console.error('Failed to copy:', err)
      // Fallback for older browsers
      const textarea = document.createElement('textarea')
      textarea.value = text
      textarea.style.position = 'fixed'
      textarea.style.opacity = '0'
      document.body.appendChild(textarea)
      textarea.select()
      try {
        document.execCommand('copy')
        document.body.removeChild(textarea)
        return true
      } catch (e) {
        document.body.removeChild(textarea)
        return false
      }
    }
  }

  /**
   * Export as markdown and copy to clipboard
   */
  async function exportAsMarkdown(decision) {
    const md = generateMarkdown(decision)
    return await copyToClipboard(md)
  }

  /**
   * Export as plain text and copy to clipboard
   */
  async function exportAsText(decision) {
    const text = generatePlainText(decision)
    return await copyToClipboard(text)
  }

  /**
   * Create print-friendly HTML content for PDF export
   */
  function createPrintContent(decision) {
    const meta = toolMeta[decision.tool] || { name: decision.tool }
    const date = new Date(decision.createdAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Decision Analysis - ${escapeHtml(decision.decision)}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; line-height: 1.6; }
          h1 { color: #1f2937; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
          h2 { color: #374151; margin-top: 24px; }
          .meta { color: #6b7280; margin-bottom: 20px; }
          .score { font-size: 24px; font-weight: bold; color: #3b82f6; }
          .recommendation { background: #eff6ff; padding: 12px; border-radius: 8px; margin: 16px 0; }
          ul { padding-left: 20px; }
          li { margin: 4px 0; }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(decision.decision)}</h1>
        <div class="meta">
          <p><strong>Tool:</strong> ${escapeHtml(meta.name)}</p>
          <p><strong>Date:</strong> ${escapeHtml(date)}</p>
        </div>
        <p class="score">Score: ${decision.score !== null ? decision.score : 'N/A'}</p>
        <div class="recommendation">
          <strong>Recommendation:</strong> ${escapeHtml(decision.recommendation)}
        </div>
        <hr>
        <p style="color: #9ca3af; font-size: 12px;">Generated by Decision Tools</p>
      </body>
      </html>
    `
    return html
  }

  /**
   * Escape HTML special characters
   */
  function escapeHtml(text) {
    const div = document.createElement('div')
    div.textContent = text
    return div.innerHTML
  }

  /**
   * Open print dialog for PDF export using safe DOM methods
   */
  function exportAsPdf(decision) {
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      const content = createPrintContent(decision)
      printWindow.document.open()
      printWindow.document.close()

      // Use DOMParser for safer content insertion
      const parser = new DOMParser()
      const doc = parser.parseFromString(content, 'text/html')

      // Copy the parsed document to the new window
      printWindow.document.replaceChild(
        printWindow.document.importNode(doc.documentElement, true),
        printWindow.document.documentElement
      )

      setTimeout(() => {
        printWindow.print()
      }, 250)
    }
  }

  return {
    generateMarkdown,
    generatePlainText,
    copyToClipboard,
    exportAsMarkdown,
    exportAsText,
    exportAsPdf
  }
}
